version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=NEXT_PUBLIC_APP_ENV
      # Uncomment the following line to disable telemetry during runtime
      # - NEXT_TELEMETRY_DISABLED=1
    restart: always
